name: Setup UI Env
description: Setup node, python and call bootstrap script

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
       
    - name: Update packages
      shell: bash
      run: |
        DEBIAN_FRONTEND=noninteractive sudo apt update

    - name: Install Python for node-sass
      shell: bash
      run: |
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends python2

    - name: Install packages
      shell: bash
      run: ./scripts/bootstrap
